"""got rid of availability table

Revision ID: 5ab0cb3b15b9
Revises: a97c400e9e6a
Create Date: 2023-11-15 17:53:14.013611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab0cb3b15b9'
down_revision = 'a97c400e9e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('availability')

    op.create_table('availability',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('property_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name='fk_availability_property_id_properties'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
