"""fixed schema

Revision ID: 78386a61cb6d
Revises: c26728bf1fd9
Create Date: 2023-11-14 15:23:13.242024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78386a61cb6d'
down_revision = 'c26728bf1fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
