"""empty message

Revision ID: 9b1fff3c7325
Revises: 7bf133a29de4
Create Date: 2023-11-20 16:46:30.118903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1fff3c7325'
down_revision = '7bf133a29de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('reservation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservation', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
