"""revised schema

Revision ID: a8643551eb37
Revises: 78386a61cb6d
Create Date: 2023-11-14 21:03:07.263760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8643551eb37'
down_revision = '78386a61cb6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_constraint('fk_availability_reseevation_id_reservations', type_='foreignkey')
        batch_op.drop_column('reseevation_id')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('pricing_per_night_in_dollars')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('airbnb_link', sa.String(), nullable=True))
        batch_op.drop_column('check_out')
        batch_op.drop_column('check_in')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('check_out', sa.DATETIME(), nullable=True))
        batch_op.drop_column('airbnb_link')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricing_per_night_in_dollars', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reseevation_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_availability_reseevation_id_reservations', 'reservations', ['reseevation_id'], ['id'])

    # ### end Alembic commands ###
