"""empty message

Revision ID: bb8dd9c6f881
Revises: 9b1fff3c7325
Create Date: 2023-11-20 16:49:37.642894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8dd9c6f881'
down_revision = '9b1fff3c7325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservation', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('reservation')

    # ### end Alembic commands ###
